### ISSUE TITLE
Sticky header implementation

### ISSUE THREAD

**Issue by bradchoate** [MLTSHP/mltshp-patterns#1302]
**Is your feature request related to a problem? Please describe.**
MLTSHP could use a navigation strip once the user scrolls through the page.

**Describe the solution you'd like**
I'd like a condensed variation of the header navigation display when the regular header scrolls out of view. This would allow consistent access from the top of the page to site navigation, so you don't have to scroll back to the top of the page to access them.

**Describe alternatives you've considered**
A sticky header might be unappealing, since it consumes a static area of the viewport. Perhaps this could be addressed by having it auto-hide after the user stops scrolling, and revealed again when resuming scrolling (could be any direction, or could just be an upward scroll).

**Additional context**
I've got nothing.

**Mock**

Here's a mock-up / prototype of what I was picturing:

![Image](https://github.com/user-attachments/assets/bd2ae875-4d6d-4bfd-9753-3e4156154647)

I'm not entirely sure if it's possible to get a pure-CSS transition from a non-docked to a docked header. I know you can use sticky positioning to achieve something like that, but I would also expect other things to adjust, like the scale of the logo for instance. Here are the adjusted styles I used, building off a "docked" CSS class being assigned to the `.site-header` element:

```css
.site-header.docked {
    backdrop-filter: blur(5px);
    background-color: rgba(0, 0, 0, 0.5);
    left: 0;
    padding: 1rem 20px;
    padding-bottom: 1rem;
    position: fixed;
    right: 0;
    top: 0;
    z-index: 1;
}

.site-header.docked .site-branding img {
    height: 60px;
    width: auto;
}

.site-header.docked .site-branding {
    margin: 0;
    margin-top: -10px;
    padding-right: 20px;
    width: auto;
}

.site-header.docked .site-nav {
    margin-top: 5px;
}

.site-header.docked .user-nav {
    display: none;
}

body:has(.site-header.docked) {
    margin-top: 125px;
}
```

As for the `.user-nav` element, that could be reserved for when you're at the top of the page, in the normal header. I tried to make it work for the condensed header, but it was too close for comfort to the new post button.

The `docked` class could be applied after scrolling down the page ~125px worth, since that would mean the header was off screen. Upon scrolling into the top 125px, the class would be removed.
