### ISSUE TITLE
Compact Peekaboo Header

### ISSUE THREAD

**Issue by spaceninja** [MLTSHP/mltshp-patterns#1327]
@heyitsal said:

> Design interactivity request for the stick header: Can you make the height shorter across the top? It looks great on mobile but on desktop, it’s around 60px high. I don’t think that much prominence is necessary anymore for users to know its there, or what it does. It would be better to shoot it down to 30px or 45px.

@bradchoate said:

> The size is identical and is that tall since the header buttons are the size they are (the size of the buttons are not altered between the docked and undocked renditions). We can alter the font size of the buttons to make them smaller for the docked version… this is how it looks if the button font size is reduced to 14px (normally 18px) and makes for a header closer to 45px tall. 14px is below the recommended minimum size for accessibility. 16px is the recommended minimum.

![Image](https://github.com/user-attachments/assets/6e2f9bd6-045f-4f84-ae86-081e8012b95c)

For that screenshot, I just applied a chrome stylesheet override of:

```css
.site-nav .btn {
    font-size: 14px;
    line-height: 1.8em;
    height: 1.8em;
}

.site-header.docked .site-branding .site-branding--icon {
    height: 1.6em;
    width: 1.6em;
}
```

@spaceninja said:

> It sounds like we need a compact button variant. I can add that and put up a PR for Al to check out that aims for more like 45px. Agreed about the accessibility concerns.
